// Convert a trial_request into a real doctor account.
// - Verifies the caller is a super-admin
// - Creates an auth user (random password) for the new doctor
// - Inserts a doctors row (slug auto-generated by trigger)
// - Grants the `admin` role to the new user
// - Marks the trial_request as converted

import { createClient } from "https://esm.sh/@supabase/supabase-js@2.45.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response(null, { headers: corsHeaders });

  try {
    const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
    const SERVICE_KEY = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
    const ANON_KEY = Deno.env.get("SUPABASE_PUBLISHABLE_KEY") || Deno.env.get("SUPABASE_ANON_KEY")!;

    const authHeader = req.headers.get("Authorization") || "";
    const token = authHeader.replace("Bearer ", "");
    if (!token) return json({ error: "Missing auth" }, 401);

    // Verify caller
    const userClient = createClient(SUPABASE_URL, ANON_KEY, {
      global: { headers: { Authorization: authHeader } },
    });
    const { data: userRes, error: userErr } = await userClient.auth.getUser(token);
    if (userErr || !userRes.user) return json({ error: "Unauthorized" }, 401);

    const admin = createClient(SUPABASE_URL, SERVICE_KEY);
    const { data: isSuper } = await admin.rpc("is_superadmin", { _user_id: userRes.user.id });
    if (!isSuper) return json({ error: "Forbidden — super-admin only" }, 403);

    const body = await req.json();
    const { trial_request_id, slug, plan_type } = body || {};
    if (!trial_request_id) return json({ error: "trial_request_id required" }, 400);

    // Load trial request
    const { data: tr, error: trErr } = await admin
      .from("trial_requests")
      .select("*")
      .eq("id", trial_request_id)
      .maybeSingle();
    if (trErr || !tr) return json({ error: "Trial request not found" }, 404);
    if (tr.status === "converted") return json({ error: "Already converted" }, 400);

    // Create or reuse auth user
    let newUserId: string | null = null;
    let randomPwd: string | null = crypto.randomUUID() + "Aa1!";
    let reusedExistingUser = false;

    const { data: created, error: createErr } = await admin.auth.admin.createUser({
      email: tr.email,
      password: randomPwd,
      email_confirm: true,
      user_metadata: { full_name: tr.full_name, phone: tr.phone },
    });

    if (createErr || !created?.user) {
      const msg = (createErr?.message || "").toLowerCase();
      const alreadyExists =
        msg.includes("already been registered") ||
        msg.includes("already registered") ||
        msg.includes("user already exists") ||
        msg.includes("duplicate");
      if (!alreadyExists) {
        return json({ error: createErr?.message || "User creation failed" }, 400);
      }

      // Look up existing user by email
      const { data: list, error: listErr } = await admin.auth.admin.listUsers({
        page: 1,
        perPage: 200,
      });
      if (listErr) return json({ error: listErr.message }, 400);
      const existing = list.users.find(
        (u) => (u.email || "").toLowerCase() === tr.email.toLowerCase()
      );
      if (!existing) return json({ error: "Email exists but user lookup failed" }, 400);
      newUserId = existing.id;
      reusedExistingUser = true;
      randomPwd = null; // don't return a password we didn't set
    } else {
      newUserId = created.user.id;
    }

    // If this user is already linked to a doctor, reuse it instead of erroring
    const { data: existingDoctor } = await admin
      .from("doctors")
      .select("*")
      .eq("user_id", newUserId)
      .maybeSingle();

    // Grant admin role
    await admin.from("user_roles").upsert(
      { user_id: newUserId, role: "admin" },
      { onConflict: "user_id,role" }
    );
    // Update profile
    await admin
      .from("profiles")
      .update({ phone: tr.phone, full_name: tr.full_name })
      .eq("user_id", newUserId);

    let doctor = existingDoctor;
    if (!doctor) {
      const insertPayload: any = {
        email: tr.email,
        user_id: newUserId,
        is_active: true,
      };
      if (slug) insertPayload.slug = slug;
      const { data: inserted, error: docErr } = await admin
        .from("doctors")
        .insert(insertPayload)
        .select()
        .single();
      if (docErr || !inserted) {
        if (!reusedExistingUser) {
          await admin.auth.admin.deleteUser(newUserId);
        }
        return json({ error: docErr?.message || "Doctor create failed" }, 400);
      }
      doctor = inserted;
    } else if (slug && existingDoctor.slug !== slug) {
      // optionally update slug if provided and different
      await admin.from("doctors").update({ slug }).eq("id", existingDoctor.id);
    }


    // Trigger create_doctor_trial may have run; ensure subscription exists and set plan_type
    await admin.from("subscriptions").upsert(
      {
        doctor_id: doctor.id,
        status: "trialing",
        trial_ends_at: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
        plan_type: plan_type || null,
      },
      { onConflict: "doctor_id" }
    );

    // Mark trial request converted
    await admin
      .from("trial_requests")
      .update({ status: "converted", converted_doctor_id: doctor.id })
      .eq("id", trial_request_id);

    // No automated email is sent — admin shares the temporary password manually.


    return json({ success: true, doctor, temp_password: randomPwd, reused_existing_user: reusedExistingUser });
  } catch (e) {
    return json({ error: String(e?.message || e) }, 500);
  }
});

function json(body: unknown, status = 200) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "Content-Type": "application/json" },
  });
}
